### ISSUE TITLE
Instalation Error

### ISSUE THREAD

**Issue by fsainovich** [Zimbra-Community/account-history#3]
100%[===================================================================================================================================================================================================>] 1.414       --.-K/s   em 0s

2017-04-13 10:23:59 (71,1 MB/s) - âpropmigr.jarâ

Exception in thread "main" java.lang.UnsupportedClassVersionError: tk/barrydegraaff/propMigr : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:648)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:272)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:68)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:207)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:201)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:200)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:325)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:296)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:270)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:406)

[zimbra@zimbra ~]$ zmcontrol -v
Release 8.7.5_GA_1764.RHEL6_64_20170314032533 RHEL6_64 FOSS edition.

**Comment by ghost** [comment]
It seems an outdated version of Java is used by default on your server.

See: https://wiki.centos.org/HowTos/JavaRuntimeEnvironment
