### ISSUE TITLE
/tmp/account-history-installer.sh: line 129: java: command not found

### ISSUE THREAD

**Issue by floydu** [Zimbra-Community/account-history#4]
When im installing the zimblet i have message that says:

/tmp/account-history-installer.sh: line 129: java: command not found

And then the installer stops

**Comment by ghost** [comment]
is this an ubuntu server?

**Comment by floydu** [comment]
Yes, Ubuntu Server 14.04, Zimbra 8.7

**Comment by ghost** [comment]
Please re-download and run the installer, thanks for reporting

**Comment by floydu** [comment]
Now i have this issue

Length: 1414 (1.4K) [application/octet-stream]
Saving to: `propmigr.jar'

100%[======================================>] 1,414       --.-K/s   in 0s

2017-04-19 09:40:03 (681 MB/s) - `propmigr.jar' saved [1414/1414]

Exception in thread "main" java.lang.UnsupportedClassVersionError: tk/barrydaff/propMigr : Unsupported major.minor version 51.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:648)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.jav2)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:272)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:68)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:207)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:201)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:200)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:325)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:296)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:270)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:

**Comment by ghost** [comment]
I just downgraded the propmigr to java 6, rerun and try again please.

**Comment by floydu** [comment]
Zimbra Account History installed successful.
You still need to restart some services to load the changes:
su - zimbra -c "zmmailboxdctl restart"


But now i cant find it in the zimlets administration page.

**Comment by floydu** [comment]
Can you help me???

**Comment by barrydegraaff** [comment]
Demo video: https://www.youtube.com/watch?v=8pVMoXkNt8c

User manual : https://barrydegraaff.github.io/owncloud/

If you want to manually deploy the zimlet:
https://github.com/Zimbra-Community/owncloud-zimlet/issues/130

**Comment by barrydegraaff** [comment]
Please ignore last comment, was for a different issue.

**Comment by ghost** [comment]
Its under tools & migration.
